// <auto-generated />
using System;
using Caisson.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caisson.Infrastructure.Migrations
{
    [DbContext(typeof(CaissonDbContext))]
    partial class CaissonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caisson.Domain.Discovery.DiscoveryJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancellation_requested");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_run");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at_utc");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid?>("ResultSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_snapshot_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("triggered_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_discovery_job");

                    b.HasIndex("RackId")
                        .IsUnique()
                        .HasDatabaseName("ux_discovery_job_rack_active")
                        .HasFilter("status IN ('Queued','InProgress')");

                    b.HasIndex("ResultSnapshotId")
                        .HasDatabaseName("ix_discovery_job_result_snapshot_id");

                    b.HasIndex("RackId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_discovery_job_rack_id_created_at");

                    b.HasIndex("RackId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_discovery_job_rack_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("discovery_job", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Discovery.DiscoveryJobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ResultSummaryJson")
                        .HasMaxLength(4096)
                        .HasColumnType("jsonb")
                        .HasColumnName("result_summary_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("step_name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_discovery_job_step");

                    b.HasIndex("JobId", "StepName")
                        .IsUnique()
                        .HasDatabaseName("ux_discovery_job_step_job_id_step_name");

                    b.ToTable("discovery_job_step", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Discovery.RackDiscoverySchedule", b =>
                {
                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<int>("JitterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("jitter_seconds");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at_utc");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.HasKey("RackId")
                        .HasName("pk_rack_discovery_schedule");

                    b.HasIndex("Enabled", "NextRunAtUtc")
                        .HasDatabaseName("ix_rack_discovery_schedule_enabled_next_run");

                    b.ToTable("rack_discovery_schedule", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.LldpNeighbour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChassisId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("chassis_id");

                    b.Property<string>("MgmtAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mgmt_address");

                    b.Property<string>("PortId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("port_id");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("SwitchPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("switch_port_id");

                    b.Property<string>("SystemName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("system_name");

                    b.HasKey("Id")
                        .HasName("pk_lldp_neighbour");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_lldp_neighbour_rack_id");

                    b.HasIndex("SwitchPortId")
                        .HasDatabaseName("ix_lldp_neighbour_switch_port_id");

                    b.HasIndex("SnapshotId", "SwitchPortId")
                        .HasDatabaseName("ix_lldp_neighbour_snapshot_id_switch_port_id");

                    b.ToTable("lldp_neighbour", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.MacAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("mac");

                    b.Property<Guid?>("NicId")
                        .HasColumnType("uuid")
                        .HasColumnName("nic_id");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_mac_address");

                    b.HasIndex("NicId")
                        .HasDatabaseName("ix_mac_address_nic_id");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_mac_address_rack_id");

                    b.HasIndex("SnapshotId", "Mac")
                        .HasDatabaseName("ix_mac_address_snapshot_id_mac");

                    b.ToTable("mac_address", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Nic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LinkState")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("link_state");

                    b.Property<string>("MacPrimary")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("mac_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_nic");

                    b.HasIndex("MacPrimary")
                        .HasDatabaseName("ix_nic_mac_primary");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_nic_rack_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_nic_server_id");

                    b.HasIndex("SnapshotId", "ServerId")
                        .HasDatabaseName("ix_nic_snapshot_id_server_id");

                    b.ToTable("nic", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_rack");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_rack_external_key");

                    b.ToTable("rack", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BmcAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bmc_address");

                    b.Property<string>("BmcType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bmc_type");

                    b.Property<string>("BmcUuid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bmc_uuid");

                    b.Property<string>("ExternalDeviceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_device_key");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hostname");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.HasIndex("BmcUuid")
                        .HasDatabaseName("ix_server_bmc_uuid");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_server_rack_id");

                    b.HasIndex("SnapshotId", "RackId")
                        .HasDatabaseName("ix_server_snapshot_id_rack_id");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Switch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalDeviceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_device_key");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("ManagementIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("management_ip");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("os_version");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<string>("Serial")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_switch");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_switch_rack_id");

                    b.HasIndex("SnapshotId", "RackId")
                        .HasDatabaseName("ix_switch_snapshot_id_rack_id");

                    b.HasIndex("SnapshotId", "Serial")
                        .IsUnique()
                        .HasDatabaseName("ux_switch_snapshot_id_serial")
                        .HasFilter("serial IS NOT NULL");

                    b.ToTable("switch", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.SwitchPort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("IsUp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_up");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("port_name");

                    b.Property<int?>("Pvid")
                        .HasColumnType("integer")
                        .HasColumnName("pvid");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("SwitchId")
                        .HasColumnType("uuid")
                        .HasColumnName("switch_id");

                    b.Property<int[]>("TaggedVlans")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("tagged_vlans");

                    b.HasKey("Id")
                        .HasName("pk_switch_port");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_switch_port_rack_id");

                    b.HasIndex("SwitchId")
                        .HasDatabaseName("ix_switch_port_switch_id");

                    b.HasIndex("SnapshotId", "SwitchId", "PortName")
                        .IsUnique()
                        .HasDatabaseName("ux_switch_port_snapshot_id_switch_id_port_name");

                    b.ToTable("switch_port", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TargetId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_topology_audit_event");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_topology_audit_event_correlation_id");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("ix_topology_audit_event_snapshot_id");

                    b.HasIndex("RackId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_topology_audit_event_rack_id_occurred_at");

                    b.ToTable("topology_audit_event", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyCandidateMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("EvidenceJson")
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_json");

                    b.Property<Guid>("NicId")
                        .HasColumnType("uuid")
                        .HasColumnName("nic_id");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid?>("SwitchPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("switch_port_id");

                    b.HasKey("Id")
                        .HasName("pk_topology_candidate_mapping");

                    b.HasIndex("NicId")
                        .HasDatabaseName("ix_topology_candidate_mapping_nic_id");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_topology_candidate_mapping_rack_id");

                    b.HasIndex("SwitchPortId")
                        .HasDatabaseName("ix_topology_candidate_mapping_switch_port_id");

                    b.HasIndex("SnapshotId", "Confidence")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_topology_candidate_mapping_snapshot_id_confidence");

                    b.HasIndex("SnapshotId", "NicId", "SwitchPortId")
                        .HasDatabaseName("ix_topology_candidate_mapping_snapshot_id_nic_id_switch_port_id");

                    b.ToTable("topology_candidate_mapping", null, t =>
                        {
                            t.HasCheckConstraint("ck_topology_candidate_mapping_confidence", "confidence >= 0.0 AND confidence <= 1.0");
                        });
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyChangeSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeCountsJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb")
                        .HasColumnName("change_counts_json");

                    b.Property<Guid?>("PreviousSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_snapshot_id");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_topology_change_summary");

                    b.HasIndex("PreviousSnapshotId")
                        .HasDatabaseName("ix_topology_change_summary_previous_snapshot_id");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_topology_change_summary_rack_id");

                    b.HasIndex("SnapshotId")
                        .IsUnique()
                        .HasDatabaseName("ix_topology_change_summary_snapshot_id");

                    b.ToTable("topology_change_summary", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyEntityDiff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("change_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DiffPayloadJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb")
                        .HasColumnName("diff_payload_json");

                    b.Property<string>("EntityStableKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("entity_stable_key");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("PreviousSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_snapshot_id");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_topology_entity_diff");

                    b.HasIndex("PreviousSnapshotId")
                        .HasDatabaseName("ix_topology_entity_diff_previous_snapshot_id");

                    b.HasIndex("RackId", "SnapshotId")
                        .HasDatabaseName("ix_topology_entity_diff_rack_id_snapshot_id");

                    b.HasIndex("RackId", "EntityType", "EntityStableKey")
                        .HasDatabaseName("ix_topology_entity_diff_rack_id_entity_type_entity_stable_key");

                    b.HasIndex("SnapshotId", "EntityType", "EntityStableKey")
                        .IsUnique()
                        .HasDatabaseName("ux_topology_entity_diff_snapshot_entity_key");

                    b.ToTable("topology_entity_diff", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_version");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_topology_snapshot");

                    b.HasIndex("RackId", "CompletedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_topology_snapshot_rack_id_completed_at");

                    b.HasIndex("RackId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_topology_snapshot_rack_id_created_at");

                    b.HasIndex("RackId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_topology_snapshot_rack_id_version");

                    b.ToTable("topology_snapshot", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Vlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uuid")
                        .HasColumnName("rack_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("VlanId")
                        .HasColumnType("integer")
                        .HasColumnName("vlan_id");

                    b.HasKey("Id")
                        .HasName("pk_vlan");

                    b.HasIndex("RackId")
                        .HasDatabaseName("ix_vlan_rack_id");

                    b.HasIndex("SnapshotId", "VlanId")
                        .HasDatabaseName("ix_vlan_snapshot_id_vlan_id");

                    b.ToTable("vlan", (string)null);
                });

            modelBuilder.Entity("Caisson.Domain.Discovery.DiscoveryJob", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_discovery_job_racks_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("ResultSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_discovery_job_snapshots_result_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Discovery.DiscoveryJobStep", b =>
                {
                    b.HasOne("Caisson.Domain.Discovery.DiscoveryJob", null)
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discovery_job_step_discovery_job_job_id");
                });

            modelBuilder.Entity("Caisson.Domain.Discovery.RackDiscoverySchedule", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithOne()
                        .HasForeignKey("Caisson.Domain.Discovery.RackDiscoverySchedule", "RackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rack_discovery_schedule_rack_rack_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.LldpNeighbour", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_lldp_neighbour_racks_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_lldp_neighbour_snapshots_snapshot_id");

                    b.HasOne("Caisson.Domain.Topology.SwitchPort", null)
                        .WithMany("LldpNeighbours")
                        .HasForeignKey("SwitchPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lldp_neighbour_switch_ports_switch_port_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.MacAddress", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Nic", null)
                        .WithMany("MacAddresses")
                        .HasForeignKey("NicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_mac_address_nics_nic_id");

                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_mac_address_racks_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mac_address_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Nic", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_nic_racks_rack_id");

                    b.HasOne("Caisson.Domain.Topology.Server", null)
                        .WithMany("Nics")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nic_servers_server_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_nic_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Server", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_server_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany("Servers")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Switch", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_switch_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany("Switches")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_switch_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.SwitchPort", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_switch_port_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_switch_port_snapshots_snapshot_id");

                    b.HasOne("Caisson.Domain.Topology.Switch", null)
                        .WithMany("Ports")
                        .HasForeignKey("SwitchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_switch_port_switch_switch_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyAuditEvent", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_topology_audit_event_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_topology_audit_event_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyCandidateMapping", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Nic", null)
                        .WithMany()
                        .HasForeignKey("NicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_topology_candidate_mapping_nic_nic_id");

                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_topology_candidate_mapping_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany("CandidateMappings")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topology_candidate_mapping_snapshots_snapshot_id");

                    b.HasOne("Caisson.Domain.Topology.SwitchPort", null)
                        .WithMany()
                        .HasForeignKey("SwitchPortId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_topology_candidate_mapping_switch_port_switch_port_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyChangeSummary", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("PreviousSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_topology_change_summary_snapshots_previous_snapshot_id");

                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_topology_change_summary_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithOne("ChangeSummary")
                        .HasForeignKey("Caisson.Domain.Topology.TopologyChangeSummary", "SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topology_change_summary_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologyEntityDiff", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("PreviousSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_topology_entity_diff_snapshots_previous_snapshot_id");

                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_topology_entity_diff_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topology_entity_diff_snapshots_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologySnapshot", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topology_snapshot_rack_rack_id");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Vlan", b =>
                {
                    b.HasOne("Caisson.Domain.Topology.Rack", null)
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_vlan_rack_rack_id");

                    b.HasOne("Caisson.Domain.Topology.TopologySnapshot", null)
                        .WithMany("Vlans")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vlan_topology_snapshot_snapshot_id");
                });

            modelBuilder.Entity("Caisson.Domain.Discovery.DiscoveryJob", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Nic", b =>
                {
                    b.Navigation("MacAddresses");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Rack", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Server", b =>
                {
                    b.Navigation("Nics");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.Switch", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.SwitchPort", b =>
                {
                    b.Navigation("LldpNeighbours");
                });

            modelBuilder.Entity("Caisson.Domain.Topology.TopologySnapshot", b =>
                {
                    b.Navigation("CandidateMappings");

                    b.Navigation("ChangeSummary");

                    b.Navigation("Servers");

                    b.Navigation("Switches");

                    b.Navigation("Vlans");
                });
#pragma warning restore 612, 618
        }
    }
}
